export type SubArea = {
    id: string;
    name: string;
    parentId: string | null; // parentId is null for top-level areas
};

export const knowledgeAreas: SubArea[] = [
    // Agricultural and Biological Sciences
    { id: '1', name: 'Agricultural and Biological Sciences', parentId: null },
    { id: '1.1', name: 'Agricultural and Biological Sciences (miscellaneous)', parentId: '1' },
    { id: '1.2', name: 'Agronomy and Crop Science', parentId: '1' },
    { id: '1.3', name: 'Animal Science and Zoology', parentId: '1' },
    { id: '1.4', name: 'Aquatic Science', parentId: '1' },
    { id: '1.5', name: 'Ecology, Evolution, Behavior and Systematics', parentId: '1' },
    { id: '1.6', name: 'Food Science', parentId: '1' },
    { id: '1.7', name: 'Forestry', parentId: '1' },
    { id: '1.8', name: 'General Agricultural and Biological Sciences', parentId: '1' },
    { id: '1.9', name: 'Horticulture', parentId: '1' },
    { id: '1.10', name: 'Insect Science', parentId: '1' },
    { id: '1.11', name: 'Plant Science', parentId: '1' },
    { id: '1.12', name: 'Soil Science', parentId: '1' },

    // Arts and Humanities
    { id: '2', name: 'Arts and Humanities', parentId: null },
    { id: '2.1', name: 'Archeology (arts and humanities)', parentId: '2' },
    { id: '2.2', name: 'Arts and Humanities (miscellaneous)', parentId: '2' },
    { id: '2.3', name: 'Classics', parentId: '2' },
    { id: '2.4', name: 'Conservation', parentId: '2' },
    { id: '2.5', name: 'General Arts and Humanities', parentId: '2' },
    { id: '2.6', name: 'History', parentId: '2' },
    { id: '2.7', name: 'History and Philosophy of Science', parentId: '2' },
    { id: '2.8', name: 'Language and Linguistics', parentId: '2' },
    { id: '2.9', name: 'Literature and Literary Theory', parentId: '2' },
    { id: '2.10', name: 'Museology', parentId: '2' },
    { id: '2.11', name: 'Music', parentId: '2' },
    { id: '2.12', name: 'Philosophy', parentId: '2' },
    { id: '2.13', name: 'Religious Studies', parentId: '2' },
    { id: '2.14', name: 'Visual Arts and Performing Arts', parentId: '2' },

    // Biochemistry, Genetics and Molecular Biology
    { id: '3', name: 'Biochemistry, Genetics and Molecular Biology', parentId: null },
    { id: '3.1', name: 'Aging', parentId: '3' },
    { id: '3.2', name: 'Biochemistry', parentId: '3' },
    { id: '3.3', name: 'Biochemistry, Genetics and Molecular Biology (miscellaneous)', parentId: '3' },
    { id: '3.4', name: 'Biophysics', parentId: '3' },
    { id: '3.5', name: 'Biotechnology', parentId: '3' },
    { id: '3.6', name: 'Cancer Research', parentId: '3' },
    { id: '3.7', name: 'Cell Biology', parentId: '3' },
    { id: '3.8', name: 'Clinical Biochemistry', parentId: '3' },
    { id: '3.9', name: 'Developmental Biology', parentId: '3' },
    { id: '3.10', name: 'Endocrinology', parentId: '3' },
    { id: '3.11', name: 'General Biochemistry, Genetics and Molecular Biology', parentId: '3' },
    { id: '3.12', name: 'Genetics', parentId: '3' },
    { id: '3.13', name: 'Molecular Biology', parentId: '3' },
    { id: '3.14', name: 'Molecular Medicine', parentId: '3' },
    { id: '3.15', name: 'Physiology', parentId: '3' },
    { id: '3.16', name: 'Structural Biology', parentId: '3' },

    // Business, Management and Accounting
    { id: '4', name: 'Business, Management and Accounting', parentId: null },
    { id: '4.1', name: 'Accounting', parentId: '4' },
    { id: '4.2', name: 'Business and International Management', parentId: '4' },
    { id: '4.3', name: 'Business, Management and Accounting (miscellaneous)', parentId: '4' },
    { id: '4.4', name: 'General Business, Management and Accounting', parentId: '4' },
    { id: '4.5', name: 'Industrial Relations', parentId: '4' },
    { id: '4.6', name: 'Management Information Systems', parentId: '4' },
    { id: '4.7', name: 'Management of Technology and Innovation', parentId: '4' },
    { id: '4.8', name: 'Marketing', parentId: '4' },
    { id: '4.9', name: 'Organizational Behavior and Human Resource Management', parentId: '4' },
    { id: '4.10', name: 'Strategy and Management', parentId: '4' },
    { id: '4.11', name: 'Tourism, Leisure and Hospitality Management', parentId: '4' },

    // Chemical Engineering
    { id: '5', name: 'Chemical Engineering', parentId: null },
    { id: '5.1', name: 'Bioengineering', parentId: '5' },
    { id: '5.2', name: 'Catalysis', parentId: '5' },
    { id: '5.3', name: 'Chemical Engineering (miscellaneous)', parentId: '5' },
    { id: '5.4', name: 'Chemical Health and Safety', parentId: '5' },
    { id: '5.5', name: 'Colloid and Surface Chemistry', parentId: '5' },
    { id: '5.6', name: 'Filtration and Separation', parentId: '5' },
    { id: '5.7', name: 'Fluid Flow and Transfer Processes', parentId: '5' },
    { id: '5.8', name: 'General Chemical Engineering', parentId: '5' },
    { id: '5.9', name: 'Process Chemistry and Technology', parentId: '5' },

    // Chemistry
    { id: '6', name: 'Chemistry', parentId: null },
    { id: '6.1', name: 'Analytical Chemistry', parentId: '6' },
    { id: '6.2', name: 'Chemistry (miscellaneous)', parentId: '6' },
    { id: '6.3', name: 'Electrochemistry', parentId: '6' },
    { id: '6.4', name: 'General Chemistry', parentId: '6' },
    { id: '6.5', name: 'Inorganic Chemistry', parentId: '6' },
    { id: '6.6', name: 'Organic Chemistry', parentId: '6' },
    { id: '6.7', name: 'Physical and Theoretical Chemistry', parentId: '6' },
    { id: '6.8', name: 'Spectroscopy', parentId: '6' },

    // Computer Science
    { id: '7', name: 'Computer Science', parentId: null },
    { id: '7.1', name: 'Artificial Intelligence', parentId: '7' },
    { id: '7.2', name: 'Computational Theory and Mathematics', parentId: '7' },
    { id: '7.3', name: 'Computer Graphics and Computer-Aided Design', parentId: '7' },
    { id: '7.4', name: 'Computer Networks and Communications', parentId: '7' },
    { id: '7.5', name: 'Computer Science (miscellaneous)', parentId: '7' },
    { id: '7.6', name: 'Computer Science Applications', parentId: '7' },
    { id: '7.7', name: 'Computer Vision and Pattern Recognition', parentId: '7' },
    { id: '7.8', name: 'General Computer Science', parentId: '7' },
    { id: '7.9', name: 'Hardware and Architecture', parentId: '7' },
    { id: '7.10', name: 'Human-Computer Interaction', parentId: '7' },
    { id: '7.11', name: 'Information Systems', parentId: '7' },
    { id: '7.12', name: 'Signal Processing', parentId: '7' },
    { id: '7.13', name: 'Software', parentId: '7' },

    // Decision Sciences
    { id: '8', name: 'Decision Sciences', parentId: null },
    { id: '8.1', name: 'Decision Sciences (miscellaneous)', parentId: '8' },
    { id: '8.2', name: 'General Decision Sciences', parentId: '8' },
    { id: '8.3', name: 'Information Systems and Management', parentId: '8' },
    { id: '8.4', name: 'Management Science and Operations Research', parentId: '8' },
    { id: '8.5', name: 'Statistics, Probability and Uncertainty', parentId: '8' },

    // Dentistry
    { id: '9', name: 'Dentistry', parentId: null },
    { id: '9.1', name: 'Dental Assisting', parentId: '9' },
    { id: '9.2', name: 'Dental Hygiene', parentId: '9' },
    { id: '9.3', name: 'Dentistry (miscellaneous)', parentId: '9' },
    { id: '9.4', name: 'General Dentistry', parentId: '9' },
    { id: '9.5', name: 'Oral Surgery', parentId: '9' },
    { id: '9.6', name: 'Orthodontics', parentId: '9' },
    { id: '9.7', name: 'Periodontics', parentId: '9' },

    // Earth and Planetary Sciences
    { id: '10', name: 'Earth and Planetary Sciences', parentId: null },
    { id: '10.1', name: 'Atmospheric Science', parentId: '10' },
    { id: '10.2', name: 'Computers in Earth Sciences', parentId: '10' },
    { id: '10.3', name: 'Earth and Planetary Sciences (miscellaneous)', parentId: '10' },
    { id: '10.4', name: 'Earth-Surface Processes', parentId: '10' },
    { id: '10.5', name: 'Economic Geology', parentId: '10' },
    { id: '10.6', name: 'General Earth and Planetary Sciences', parentId: '10' },
    { id: '10.7', name: 'Geochemistry and Petrology', parentId: '10' },
    { id: '10.8', name: 'Geology', parentId: '10' },
    { id: '10.9', name: 'Geophysics', parentId: '10' },
    { id: '10.10', name: 'Geotechnical Engineering and Engineering Geology', parentId: '10' },
    { id: '10.11', name: 'Oceanography', parentId: '10' },
    { id: '10.12', name: 'Paleontology', parentId: '10' },
    { id: '10.13', name: 'Space and Planetary Science', parentId: '10' },
    { id: '10.14', name: 'Stratigraphy', parentId: '10' },

    // Economics, Econometrics and Finance
    { id: '11', name: 'Economics, Econometrics and Finance', parentId: null },
    { id: '11.1', name: 'Economics and Econometrics', parentId: '11' },
    { id: '11.2', name: 'Economics, Econometrics and Finance (miscellaneous)', parentId: '11' },
    { id: '11.3', name: 'Finance', parentId: '11' },
    { id: '11.4', name: 'General Economics, Econometrics and Finance', parentId: '11' },
    { id: '11.5', name: 'Energy', parentId: '11' },
    { id: '11.6', name: 'Energy (miscellaneous)', parentId: '11' },
    { id: '11.7', name: 'Energy Engineering and Power Technology', parentId: '11' },
    { id: '11.8', name: 'Fuel Technology', parentId: '11' },
    { id: '11.9', name: 'General Energy', parentId: '11' },
    { id: '11.10', name: 'Nuclear Energy and Engineering', parentId: '11' },
    { id: '11.11', name: 'Renewable Energy, Sustainability and the Environment', parentId: '11' },

    // Engineering
    { id: '12', name: 'Engineering', parentId: null },
    { id: '12.1', name: 'Aerospace Engineering', parentId: '12' },
    { id: '12.2', name: 'Architecture', parentId: '12' },
    { id: '12.3', name: 'Automotive Engineering', parentId: '12' },
    { id: '12.4', name: 'Biomedical Engineering', parentId: '12' },
    { id: '12.5', name: 'Building and Construction', parentId: '12' },
    { id: '12.6', name: 'Civil and Structural Engineering', parentId: '12' },
    { id: '12.7', name: 'Computational Mechanics', parentId: '12' },
    { id: '12.8', name: 'Control and Systems Engineering', parentId: '12' },
    { id: '12.9', name: 'Electrical and Electronic Engineering', parentId: '12' },
    { id: '12.10', name: 'Engineering (miscellaneous)', parentId: '12' },
    { id: '12.11', name: 'General Engineering', parentId: '12' },
    { id: '12.12', name: 'Industrial and Manufacturing Engineering', parentId: '12' },
    { id: '12.13', name: 'Mechanical Engineering', parentId: '12' },
    { id: '12.14', name: 'Mechanics of Materials', parentId: '12' },
    { id: '12.15', name: 'Media Technology', parentId: '12' },
    { id: '12.16', name: 'Ocean Engineering', parentId: '12' },
    { id: '12.17', name: 'Safety, Risk, Reliability and Quality', parentId: '12' },

    // Environmental Science
    { id: '13', name: 'Environmental Science', parentId: null },
    { id: '13.1', name: 'Ecological Modeling', parentId: '13' },
    { id: '13.2', name: 'Ecology', parentId: '13' },
    { id: '13.3', name: 'Environmental Chemistry', parentId: '13' },
    { id: '13.4', name: 'Environmental Engineering', parentId: '13' },
    { id: '13.5', name: 'Environmental Science (miscellaneous)', parentId: '13' },
    { id: '13.6', name: 'General Environmental Science', parentId: '13' },
    { id: '13.7', name: 'Global and Planetary Change', parentId: '13' },
    { id: '13.8', name: 'Health, Toxicology and Mutagenesis', parentId: '13' },
    { id: '13.9', name: 'Management, Monitoring, Policy and Law', parentId: '13' },
    { id: '13.10', name: 'Nature and Landscape Conservation', parentId: '13' },
    { id: '13.11', name: 'Pollution', parentId: '13' },
    { id: '13.12', name: 'Waste Management and Disposal', parentId: '13' },
    { id: '13.13', name: 'Water Science and Technology', parentId: '13' },

    // Health Professions
    { id: '14', name: 'Health Professions', parentId: null },
    { id: '14.1', name: 'Chiropractics', parentId: '14' },
    { id: '14.2', name: 'Complementary and Manual Therapy', parentId: '14' },
    { id: '14.3', name: 'Emergency Medical Services', parentId: '14' },
    { id: '14.4', name: 'General Health Professions', parentId: '14' },
    { id: '14.5', name: 'Health Information Management', parentId: '14' },
    { id: '14.6', name: 'Health Professions (miscellaneous)', parentId: '14' },
    { id: '14.7', name: 'Medical Assisting and Transcription', parentId: '14' },
    { id: '14.8', name: 'Medical Laboratory Technology', parentId: '14' },
    { id: '14.9', name: 'Medical Terminology', parentId: '14' },
    { id: '14.10', name: 'Occupational Therapy', parentId: '14' },
    { id: '14.11', name: 'Optometry', parentId: '14' },
    { id: '14.12', name: 'Pharmacy', parentId: '14' },
    { id: '14.13', name: 'Physical Therapy, Sports Therapy and Rehabilitation', parentId: '14' },
    { id: '14.14', name: 'Podiatry', parentId: '14' },
    { id: '14.15', name: 'Radiological and Ultrasound Technology', parentId: '14' },
    { id: '14.16', name: 'Respiratory Care', parentId: '14' },
    { id: '14.17', name: 'Speech and Hearing', parentId: '14' },

    // Immunology and Microbiology
    { id: '15', name: 'Immunology and Microbiology', parentId: null },
    { id: '15.1', name: 'Applied Microbiology and Biotechnology', parentId: '15' },
    { id: '15.2', name: 'General Immunology and Microbiology', parentId: '15' },
    { id: '15.3', name: 'Immunology', parentId: '15' },
    { id: '15.4', name: 'Immunology and Microbiology (miscellaneous)', parentId: '15' },
    { id: '15.5', name: 'Microbiology', parentId: '15' },
    { id: '15.6', name: 'Parasitology', parentId: '15' },
    { id: '15.7', name: 'Virology', parentId: '15' },

    // Materials Science
    { id: '16', name: 'Materials Science', parentId: null },
    { id: '16.1', name: 'Biomaterials', parentId: '16' },
    { id: '16.2', name: 'Ceramics and Composites', parentId: '16' },
    { id: '16.3', name: 'Electronic, Optical and Magnetic Materials', parentId: '16' },
    { id: '16.4', name: 'General Materials Science', parentId: '16' },
    { id: '16.5', name: 'Materials Chemistry', parentId: '16' },
    { id: '16.6', name: 'Materials Science (miscellaneous)', parentId: '16' },
    { id: '16.7', name: 'Metals and Alloys', parentId: '16' },
    { id: '16.8', name: 'Polymers and Plastics', parentId: '16' },
    { id: '16.9', name: 'Surfaces, Coatings and Films', parentId: '16' },

    // Mathematics
    { id: '17', name: 'Mathematics', parentId: null },
    { id: '17.1', name: 'Algebra and Number Theory', parentId: '17' },
    { id: '17.2', name: 'Analysis', parentId: '17' },
    { id: '17.3', name: 'Applied Mathematics', parentId: '17' },
    { id: '17.4', name: 'Computational Mathematics', parentId: '17' },
    { id: '17.5', name: 'Control and Optimization', parentId: '17' },
    { id: '17.6', name: 'Discrete Mathematics and Combinatorics', parentId: '17' },
    { id: '17.7', name: 'General Mathematics', parentId: '17' },
    { id: '17.8', name: 'Geometry and Topology', parentId: '17' },
    { id: '17.9', name: 'Logic', parentId: '17' },
    { id: '17.10', name: 'Mathematical Physics', parentId: '17' },
    { id: '17.11', name: 'Mathematics (miscellaneous)', parentId: '17' },
    { id: '17.12', name: 'Modeling and Simulation', parentId: '17' },
    { id: '17.13', name: 'Numerical Analysis', parentId: '17' },
    { id: '17.14', name: 'Statistics and Probability', parentId: '17' },
    { id: '17.15', name: 'Theoretical Computer Science', parentId: '17' },

    // Medicine
    { id: '18', name: 'Medicine', parentId: null },
    { id: '18.1', name: 'Anatomy', parentId: '18' },
    { id: '18.2', name: 'Anesthesiology and Pain Medicine', parentId: '18' },
    { id: '18.3', name: 'Biochemistry (medical)', parentId: '18' },
    { id: '18.4', name: 'Cardiology and Cardiovascular Medicine', parentId: '18' },
    { id: '18.5', name: 'Complementary and Alternative Medicine', parentId: '18' },
    { id: '18.6', name: 'Critical Care and Intensive Care Medicine', parentId: '18' },
    { id: '18.7', name: 'Dermatology', parentId: '18' },
    { id: '18.8', name: 'Drug Guides', parentId: '18' },
    { id: '18.9', name: 'Embryology', parentId: '18' },
    { id: '18.10', name: 'Emergency Medicine', parentId: '18' },
    { id: '18.11', name: 'Endocrinology, Diabetes and Metabolism', parentId: '18' },
    { id: '18.12', name: 'Epidemiology', parentId: '18' },
    { id: '18.13', name: 'Family Practice', parentId: '18' },
    { id: '18.14', name: 'Gastroenterology', parentId: '18' },
    { id: '18.15', name: 'General Medicine', parentId: '18' },
    { id: '18.16', name: 'Genetics (clinical)', parentId: '18' },
    { id: '18.17', name: 'Geriatrics and Gerontology', parentId: '18' },
    { id: '18.18', name: 'Health Informatics', parentId: '18' },
    { id: '18.19', name: 'Health Policy', parentId: '18' },
    { id: '18.20', name: 'Hematology', parentId: '18' },
    { id: '18.21', name: 'Hepatology', parentId: '18' },
    { id: '18.22', name: 'Histology', parentId: '18' },
    { id: '18.23', name: 'Immunology and Allergy', parentId: '18' },
    { id: '18.24', name: 'Infectious Diseases', parentId: '18' },
    { id: '18.25', name: 'Internal Medicine', parentId: '18' },
    { id: '18.26', name: 'Medicine (miscellaneous)', parentId: '18' },
    { id: '18.27', name: 'Microbiology (medical)', parentId: '18' },
    { id: '18.28', name: 'Nephrology', parentId: '18' },
    { id: '18.29', name: 'Neurology (clinical)', parentId: '18' },
    { id: '18.30', name: 'Obstetrics and Gynecology', parentId: '18' },
    { id: '18.31', name: 'Oncology', parentId: '18' },
    { id: '18.32', name: 'Ophthalmology', parentId: '18' },
    { id: '18.33', name: 'Orthopedics and Sports Medicine', parentId: '18' },
    { id: '18.34', name: 'Otorhinolaryngology', parentId: '18' },
    { id: '18.35', name: 'Pathology and Forensic Medicine', parentId: '18' },
    { id: '18.36', name: 'Pediatrics, Perinatology and Child Health', parentId: '18' },
    { id: '18.37', name: 'Pharmacology (medical)', parentId: '18' },
    { id: '18.38', name: 'Physiology (medical)', parentId: '18' },
    { id: '18.39', name: 'Psychiatry and Mental Health', parentId: '18' },
    { id: '18.40', name: 'Public Health, Environmental and Occupational Health', parentId: '18' },
    { id: '18.41', name: 'Pulmonary and Respiratory Medicine', parentId: '18' },
    { id: '18.42', name: 'Radiology, Nuclear Medicine and Imaging', parentId: '18' },
    { id: '18.43', name: 'Rehabilitation', parentId: '18' },
    { id: '18.44', name: 'Reproductive Medicine', parentId: '18' },
    { id: '18.45', name: 'Reviews and References (medical)', parentId: '18' },
    { id: '18.46', name: 'Rheumatology', parentId: '18' },
    { id: '18.47', name: 'Surgery', parentId: '18' },
    { id: '18.48', name: 'Transplantation', parentId: '18' },
    { id: '18.49', name: 'Urology', parentId: '18' },

    // Multidisciplinary
    { id: '19', name: 'Multidisciplinary', parentId: null },
    { id: '19.1', name: 'Multidisciplinary', parentId: '19' },

    // Neuroscience
    { id: '20', name: 'Neuroscience', parentId: null },
    { id: '20.1', name: 'Behavioral Neuroscience', parentId: '20' },
    { id: '20.2', name: 'Biological Psychiatry', parentId: '20' },
    { id: '20.3', name: 'Cellular and Molecular Neuroscience', parentId: '20' },
    { id: '20.4', name: 'Cognitive Neuroscience', parentId: '20' },
    { id: '20.5', name: 'Developmental Neuroscience', parentId: '20' },
    { id: '20.6', name: 'Endocrine and Autonomic Systems', parentId: '20' },
    { id: '20.7', name: 'General Neuroscience', parentId: '20' },
    { id: '20.8', name: 'Neurology', parentId: '20' },
    { id: '20.9', name: 'Neuroscience (miscellaneous)', parentId: '20' },
    { id: '20.10', name: 'Sensory Systems', parentId: '20' },

    // Nursing
    { id: '21', name: 'Nursing', parentId: null },
    { id: '21.1', name: 'Advanced and Specialized Nursing', parentId: '21' },
    { id: '21.2', name: 'Assessment and Diagnosis', parentId: '21' },
    { id: '21.3', name: 'Care Planning', parentId: '21' },
    { id: '21.4', name: 'Community and Home Care', parentId: '21' },
    { id: '21.5', name: 'Critical Care Nursing', parentId: '21' },
    { id: '21.6', name: 'Emergency Nursing', parentId: '21' },
    { id: '21.7', name: 'Fundamentals and Skills', parentId: '21' },
    { id: '21.8', name: 'General Nursing', parentId: '21' },
    { id: '21.9', name: 'Gerontology', parentId: '21' },
    { id: '21.10', name: 'Issues, Ethics and Legal Aspects', parentId: '21' },
    { id: '21.11', name: 'LPN and LVN', parentId: '21' },
    { id: '21.12', name: 'Leadership and Management', parentId: '21' },
    { id: '21.13', name: 'Maternity and Midwifery', parentId: '21' },
    { id: '21.14', name: 'Medical and Surgical Nursing', parentId: '21' },
    { id: '21.15', name: 'Nurse Assisting', parentId: '21' },
    { id: '21.16', name: 'Nursing (miscellaneous)', parentId: '21' },
    { id: '21.17', name: 'Nutrition and Dietetics', parentId: '21' },
    { id: '21.18', name: 'Oncology (nursing)', parentId: '21' },
    { id: '21.19', name: 'Pathophysiology', parentId: '21' },
    { id: '21.20', name: 'Pediatrics', parentId: '21' },
    { id: '21.21', name: 'Pharmacology (nursing)', parentId: '21' },
    { id: '21.22', name: 'Psychiatric Mental Health', parentId: '21' },
    { id: '21.23', name: 'Research and Theory', parentId: '21' },
    { id: '21.24', name: 'Review and Exam Preparation', parentId: '21' },

    // Pharmacology, Toxicology and Pharmaceutics
    { id: '22', name: 'Pharmacology, Toxicology and Pharmaceutics', parentId: null },
    { id: '22.1', name: 'Drug Discovery', parentId: '22' },
    { id: '22.2', name: 'General Pharmacology, Toxicology and Pharmaceutics', parentId: '22' },
    { id: '22.3', name: 'Pharmaceutical Science', parentId: '22' },
    { id: '22.4', name: 'Pharmacology', parentId: '22' },
    { id: '22.5', name: 'Pharmacology, Toxicology and Pharmaceutics (miscellaneous)', parentId: '22' },
    { id: '22.6', name: 'Toxicology', parentId: '22' },

    // Physics and Astronomy
    { id: '23', name: 'Physics and Astronomy', parentId: null },
    { id: '23.1', name: 'Acoustics and Ultrasonics', parentId: '23' },
    { id: '23.2', name: 'Astronomy and Astrophysics', parentId: '23' },
    { id: '23.3', name: 'Atomic and Molecular Physics, and Optics', parentId: '23' },
    { id: '23.4', name: 'Condensed Matter Physics', parentId: '23' },
    { id: '23.5', name: 'General Physics and Astronomy', parentId: '23' },
    { id: '23.6', name: 'Instrumentation', parentId: '23' },
    { id: '23.7', name: 'Nuclear and High Energy Physics', parentId: '23' },
    { id: '23.8', name: 'Physics and Astronomy (miscellaneous)', parentId: '23' },
    { id: '23.9', name: 'Radiation', parentId: '23' },
    { id: '23.10', name: 'Statistical and Nonlinear Physics', parentId: '23' },
    { id: '23.11', name: 'Surfaces and Interfaces', parentId: '23' },

    // Psychology
    { id: '24', name: 'Psychology', parentId: null },
    { id: '24.1', name: 'Applied Psychology', parentId: '24' },
    { id: '24.2', name: 'Clinical Psychology', parentId: '24' },
    { id: '24.3', name: 'Developmental and Educational Psychology', parentId: '24' },
    { id: '24.4', name: 'Experimental and Cognitive Psychology', parentId: '24' },
    { id: '24.5', name: 'General Psychology', parentId: '24' },
    { id: '24.6', name: 'Neuropsychology and Physiological Psychology', parentId: '24' },
    { id: '24.7', name: 'Psychology (miscellaneous)', parentId: '24' },
    { id: '24.8', name: 'Social Psychology', parentId: '24' },

    // Social Sciences
    { id: '25', name: 'Social Sciences', parentId: null },
    { id: '25.1', name: 'Anthropology', parentId: '25' },
    { id: '25.2', name: 'Archeology', parentId: '25' },
    { id: '25.3', name: 'Communication', parentId: '25' },
    { id: '25.4', name: 'Cultural Studies', parentId: '25' },
    { id: '25.5', name: 'Demography', parentId: '25' },
    { id: '25.6', name: 'Development', parentId: '25' },
    { id: '25.7', name: 'Education', parentId: '25' },
    { id: '25.8', name: 'Gender Studies', parentId: '25' },
    { id: '25.9', name: 'General Social Sciences', parentId: '25' },
    { id: '25.10', name: 'Geography, Planning and Development', parentId: '25' },
    { id: '25.11', name: 'Health (social science)', parentId: '25' },
    { id: '25.12', name: 'Human Factors and Ergonomics', parentId: '25' },
    { id: '25.13', name: 'Law', parentId: '25' },
    { id: '25.14', name: 'Library and Information Sciences', parentId: '25' },
    { id: '25.15', name: 'Life-span and Life-course Studies', parentId: '25' },
    { id: '25.16', name: 'Linguistics and Language', parentId: '25' },
    { id: '25.17', name: 'Political Science and International Relations', parentId: '25' },
    { id: '25.18', name: 'Public Administration', parentId: '25' },
    { id: '25.19', name: 'Safety Research', parentId: '25' },
    { id: '25.20', name: 'Social Sciences (miscellaneous)', parentId: '25' },
    { id: '25.21', name: 'Sociology and Political Science', parentId: '25' },
    { id: '25.22', name: 'Transportation', parentId: '25' },
    { id: '25.23', name: 'Urban Studies', parentId: '25' },

    // Veterinary
    { id: '26', name: 'Veterinary', parentId: null },
    { id: '26.1', name: 'Equine', parentId: '26' },
    { id: '26.2', name: 'Food Animals', parentId: '26' },
    { id: '26.3', name: 'General Veterinary', parentId: '26' },
    { id: '26.4', name: 'Small Animals', parentId: '26' },
    { id: '26.5', name: 'Veterinary (miscellaneous)', parentId: '26' },

];



