import type { UserProfile } from "$lib/types/UserProfile";

const userProfiles: UserProfile[] = [
    {
        id: "AliceJohnson",
        name: "Alice Johnson",
        email: "alice@example.com",
        password: "password123",
        profilePicture: "https://media.istockphoto.com/id/1369508766/pt/foto/beautiful-successful-latin-woman-smiling.jpg?s=612x612&w=0&k=20&c=FwKAb3g3-xgzsbyTcgjluJlGS1wBMXMg1hT2sB-gn2A=",
        interestAreas: ["Biology", "Physics", "Technology"],
        institution: "University of Life Sciences",
        title: "Senior Research Scientist",
        bio: "Alice Johnson has over 15 years of experience in the field of life sciences, specializing in the intersection of biology and technology. She has led numerous research projects on bioinformatics and biophysics, contributing to major scientific journals. Alice is passionate about leveraging technology to solve complex biological problems and mentors young scientists in her free time.",
    },
    {
        id: "BobSmith",
        name: "Bob Smith",
        email: "bob@example.com",
        password: "securepassword",
        profilePicture: "https://media.istockphoto.com/id/1485546774/pt/foto/bald-man-smiling-at-camera-standing-with-arms-crossed.jpg?s=612x612&w=0&k=20&c=lXDGScuGZHB43G9RC6o0_8J0pqR05K5RSrV2K3JG0nU=",
        interestAreas: ["Medicine", "Chemistry", "Environment"],
        institution: "Global Medical Institute",
        title: "Chief Medical Officer",
        bio: "Dr. Bob Smith is a leading expert in medical research and environmental health. With a career spanning two decades, he has published extensively on the impacts of chemical pollutants on human health. Dr. Smith also plays a crucial role in policy advisory committees aimed at improving public health standards globally.",
    },
    {
        id: "CharlieBrown",
        name: "Charlie Brown",
        email: "charlie@example.com",
        password: "123456",
        profilePicture: "https://media.istockphoto.com/id/1331257339/pt/foto/portrait-of-happy-mature-man-wearing-spectacles-and-looking-at-camera-indoor.jpg?s=612x612&w=0&k=20&c=UGyByb-PyXNZY0ho8U45PfMoqBKxbKkMsWxtVFbAdnM=",
        interestAreas: ["Astronomy", "Artificial Intelligence", "Neuroscience"],
        institution: "Institute of Advanced Studies",
        title: "Assistant Professor of Astrophysics",
        bio: "Charlie Brown is an emerging scholar in the fields of astrophysics and artificial intelligence. His research focuses on the use of AI to analyze astronomical data and uncover new insights about the universe. Charlie is also interested in the applications of neuroscience in understanding cognitive processes and has received multiple grants for his interdisciplinary research.",
    },
    {
        id: "Dr.JohnSmith",
        name: "Dr. John Smith",
        email: "john.smith@example.com",
        password: "password123",
        profilePicture: "https://media.istockphoto.com/id/1464048328/pt/foto/business-man-looking-outside-the-window-in-an-office.jpg?s=612x612&w=0&k=20&c=vbhiFg3EhhlI4bzJmELXUN1dbeei_hVPnd58jW-B3Ms=",
        interestAreas: ["Genetics", "Biotechnology", "Bioinformatics"],
        institution: "Harvard University",
        title: "Professor of Genetics",
        bio: "Dr. John Smith is a renowned geneticist with over 20 years of experience in the field. He has published extensively on gene editing technologies and their applications in medicine. At Harvard University, he leads a research team focused on CRISPR and gene therapy, aiming to find cures for genetic disorders.",
    },
    {
        id: "Dr.AliceWalker",
        name: "Dr. Alice Walker",
        email: "alice.walker@example.com",
        password: "securepassword",
        profilePicture: "https://media.istockphoto.com/id/1915382108/pt/foto/smiling-friendly-confident-millennial-caucasian-lady-manager-teacher-in-formal-wear-with.jpg?b=1&s=170667a&w=0&k=20&c=Bgs0ivlQI9W_MBEGniNHyc4Q1K7BMFhLo-5EVBGhccc=",
        interestAreas: ["Literature", "Cultural Studies", "Gender Studies"],
        institution: "Stanford University",
        title: "Professor of Literature",
        bio: "Dr. Alice Walker is a distinguished scholar in literature and cultural studies. Her research explores the intersection of literature, culture, and gender, with a particular focus on marginalized voices. Dr. Walker's work has received numerous awards and she is a sought-after speaker at international conferences.",
    },
    {
        id: "Dr.SarahLee",
        name: "Dr. Sarah Lee",
        email: "sarah.lee@example.com",
        password: "123456",
        profilePicture: "https://media.istockphoto.com/id/1289220545/pt/foto/beautiful-woman-smiling-with-crossed-arms.jpg?s=612x612&w=0&k=20&c=J8IOft88XNXaMMjGBZUbbUVPPiDkxXO2uX5lxuWFRbM=",
        interestAreas: ["Environmental Science", "Climate Change", "Sustainability"],
        institution: "University of California, Berkeley",
        title: "Associate Professor of Environmental Science",
        bio: "Dr. Sarah Lee's research focuses on climate change and sustainable practices. At UC Berkeley, she leads several initiatives aimed at reducing carbon footprints and promoting eco-friendly technologies. Dr. Lee's work has been pivotal in shaping environmental policies at both state and national levels.",
    },
    {
        id: "Dr.DavidMiller",
        name: "Dr. David Miller",
        email: "david.miller@example.com",
        password: "password789",
        profilePicture: "https://media.istockphoto.com/id/1445597021/pt/foto/black-man-phone-and-social-media-in-city-reading-text-message-or-communication-on-social.jpg?s=612x612&w=0&k=20&c=dFU-yhp9KcsQMBtj3mGrpuuVZPtA2JQSCF88_6FPs3o=",
        interestAreas: ["Physics", "Quantum Mechanics", "Theoretical Physics"],
        institution: "Massachusetts Institute of Technology",
        title: "Professor of Physics",
        bio: "Dr. David Miller is a leading theoretical physicist whose work on quantum mechanics has earned him international acclaim. At MIT, he teaches and conducts research on the fundamental aspects of quantum theory, contributing to groundbreaking advancements in the field.",
    },
    {
        id: "Dr.LauraAnderson",
        name: "Dr. Laura Anderson",
        email: "laura.anderson@example.com",
        password: "mypassword",
        profilePicture: "https://media.istockphoto.com/id/1434212178/pt/foto/middle-eastern-lady-using-laptop-working-online-sitting-in-office.jpg?s=612x612&w=0&k=20&c=cqKEcdL2Rb0dilodWnJf7udizXbpyv_q8EaF94YRUqQ=",
        interestAreas: ["Psychology", "Cognitive Science", "Behavioral Neuroscience"],
        institution: "Yale University",
        title: "Professor of Psychology",
        bio: "Dr. Laura Anderson is a prominent psychologist specializing in cognitive science and behavioral neuroscience. Her research at Yale University delves into the mechanisms of human cognition and behavior, with an emphasis on mental health and therapeutic interventions.",
    },
    {
        id: "Dr.SarahLee2",
        name: "Dr. Sarah Lee",
        email: "sarah.lee2@example.com",
        password: "securepass",
        profilePicture: "https://via.placeholder.com/150",
        interestAreas: ["Microbiology", "Infectious Diseases", "Immunology"],
        institution: "Johns Hopkins University",
        title: "Associate Professor of Microbiology",
        bio: "Dr. Sarah Lee is an expert in microbiology and infectious diseases, with a focus on immunology. At Johns Hopkins University, her research contributes to understanding the mechanisms of pathogen-host interactions and developing new treatments for infectious diseases.",
    },
    {
        id: "Dr.EmilyWilson",
        name: "Dr. Emily Wilson",
        email: "emily.wilson@example.com",
        password: "emilypass",
        profilePicture: "https://media.istockphoto.com/id/1298074216/pt/foto/portrait-of-female-architect.jpg?s=612x612&w=0&k=20&c=XqxnQoGfQYWk1O7mrBM2ZX_zLH3a_mKHr8fMQnTJhR0=",
        interestAreas: ["Sociology", "Urban Studies", "Public Policy"],
        institution: "University of Chicago",
        title: "Professor of Sociology",
        bio: "Dr. Emily Wilson is a sociologist with a keen interest in urban studies and public policy. Her work at the University of Chicago examines the social dynamics of urban environments and informs policies aimed at improving urban living conditions.",
    },
    {
        id: "Dr.MichaelBrown",
        name: "Dr. Michael Brown",
        email: "michael.brown@example.com",
        password: "mikepass123",
        profilePicture: "https://media.istockphoto.com/id/1307241137/pt/foto/cheerful-senior-man-in-casual-clothing.jpg?s=612x612&w=0&k=20&c=ewbktIrSpzg6e2rtVoT2Q6UgdH8SGUCRG3DkRWDGAe0=",
        interestAreas: ["Engineering", "Robotics", "Artificial Intelligence"],
        institution: "California Institute of Technology",
        title: "Professor of Engineering",
        bio: "Dr. Michael Brown is a pioneering engineer in the fields of robotics and artificial intelligence. His research at Caltech focuses on developing advanced robotic systems and AI algorithms, pushing the boundaries of what machines can achieve.",
    },
    {
        id: "Dr.OliviaParker",
        name: "Dr. Olivia Parker",
        email: "olivia.parker@example.com",
        password: "oliviapass",
        profilePicture: "https://media.istockphoto.com/id/1587604256/pt/foto/portrait-lawyer-and-black-woman-with-tablet-smile-and-happy-in-office-workplace-african.jpg?s=612x612&w=0&k=20&c=2K847J5k53DJplkBCqMBuV6VCaeNouCnnhXsw25aEz8=",
        interestAreas: ["Economics", "Finance", "Business Administration"],
        institution: "London School of Economics",
        title: "Professor of Economics",
        bio: "Dr. Olivia Parker is an esteemed economist whose research spans finance and business administration. At the London School of Economics, she provides insights into global economic trends and advises on financial policies, contributing significantly to the academic and business communities.",
    }
];


export { userProfiles };
